{% set name = "modin" %}
{% set version = "0.9.1" %}

package:
  name: modin-packages
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6a31ab403ca47eb1d0d1c42a7a7faa181ee85154afe1d264a07c06da2de633ff

build:
  number: 1
  # noarch disabled because the recipe now has selector for Ray, see below
  # noarch: python
  skip: true  # [py<37]

# the outputs map the modin options on PyPI (see upstream definition
# https://github.com/modin-project/modin/blob/0.9.0/setup.py#L60-L67)
# from "modin[<option>]" to "modin-<option>" as a conda-forge package
outputs:
  - name: modin-all
    requirements:
      host:
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - {{ pin_subpackage('modin-dask', exact=True) }}
        # ray does not have OSX builds yet
        - {{ pin_subpackage('modin-ray', exact=True) }}  # [not osx]
        #- {{ pin_subpackage('modin-remote', exact=True) }}       # turned off for now, see below
        #- {{ pin_subpackage('modin-spreadsheet', exact=True) }}  # turned off for now, see below
    test:
      imports:
        # dummy test; actual tests are in subpackages
        - modin

  # compatibility with packagename before split into options
  - name: modin
    requirements:
      host:
      run:
        - python
        # modin needs at least one engine; use dask as it is more light-weight than ray
        - {{ pin_subpackage('modin-dask', exact=True) }}
    test:
      imports:
        - modin
        - modin.pandas

  - name: modin-core
    build:
      script: 'python -m pip install . --no-deps --ignore-installed -vv'
    requirements:
      host:
        - pip
        - python
      run:
        - python
        - packaging
        - pandas ==1.2.3
    test:
      commands:
        # cannot import modin because it needs an engine (dask or ray)
        # TODO: add core-specific tests!
        - exit 0

  - name: modin-dask
    build:
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - dask >=2.12.0
        - distributed >=2.12.0
    test:
      imports:
        # are there more specific imports?!
        - modin

  - name: modin-ray
    build:
      # there is no Ray in conda-forge for MacOS yet, see conda-forge/ray-packages-feedstock#2
      skip: true  # [osx]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - ray-core >=1.0
        - pyarrow ==1.0
    test:
      imports:
        # are there more specific imports?!
        - modin

  - name: modin-remote
    build:
      # dependency rpyc is not in conda-forge yet
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - boto3 ==1.4.8
        - cloudpickle ==1.4.1
        - rpyc ==4.1.5
    test:
      imports:
        # are there more specific imports?!
        - modin

  # TODO: resolve conflict modin[spreadsheet] vs. modin-spreadsheet
  - name: modin-spreadsheet
    build:
      # dependency modin-spreadsheet is not in conda-forge yet
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('modin-core', exact=True) }}
        - modin-spreadsheet >=0.1.0
    test:
      imports:
        # are there more specific imports?!
        - modin

about:
  home: https://github.com/modin-project/modin
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Speed up your Pandas workflows by changing a single line of code
  doc_url: https://modin.readthedocs.io/
  dev_url: https://github.com/modin-project/modin

extra:
  recipe-maintainers:
    - devin-petersohn
    - h-vetinari
  feedstock-name: modin
